# Generated by Django 3.2.4 on 2021-06-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='slug',
        ),
        migrations.AddField(
            model_name='productos',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
