# Generated by Django 3.2.4 on 2021-06-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
