# Generated by Django 3.2.4 on 2021-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_contacto_avisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='featured',
        ),
    ]
