# Generated by Django 3.2.4 on 2021-07-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20210705_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
