# Generated by Django 3.2.4 on 2021-07-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_orderitem_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
